<?php
define('_DB_SERVER_', 'localhost');
define('_DB_NAME_', 'prestashop');
define('_DB_USER_', 'root');
define('_DB_PASSWD_', 'root');
define('_DB_PREFIX_', 'ps_');
define('_MYSQL_ENGINE_', 'InnoDB');
define('_PS_CACHING_SYSTEM_', 'CacheMemcache');
define('_PS_CACHE_ENABLED_', '0');
define('_MEDIA_SERVER_1_', '');
define('_MEDIA_SERVER_2_', '');
define('_MEDIA_SERVER_3_', '');
define('_COOKIE_KEY_', 'hFKcEMNN7YBgLYP2chn2zMn5946iP2J3VI0h7WPHfbicGoPsf0iMvukg');
define('_COOKIE_IV_', 'hEcvvjit');
define('_PS_CREATION_DATE_', '2014-09-11');
if (!defined('_PS_VERSION_'))
	define('_PS_VERSION_', '1.6.0.9');
define('_RIJNDAEL_KEY_', '4e0pgRA6Cg1vd4d4Tst9ATVINKW9b8NG');
define('_RIJNDAEL_IV_', '+5ypvTYR0cr9qao7ylgtPQ==');
